# GitHub Actions Workflow Template for UF COE Web Mapper Crawler
# 
# This is a TEMPLATE ONLY - it is NOT active by default.
# 
# To enable:
# 1. Rename this file from crawler.yml.template to crawler.yml
# 2. Uncomment the commit/push step below if you want automated commits
# 3. Set a cron schedule (currently commented)
# 4. Grant workflow write permissions:
#    Repo Settings → Actions → General → Workflow permissions → Read and write
#
# WARNING: Do not enable this until you are ready for automated crawls and commits.

name: Web Ecosystem Crawler

# Trigger options
on:
  # Daily automatic crawl at 4 AM Eastern Time (9 AM UTC)
  schedule:
    - cron: '0 9 * * *'  # Daily at 9 AM UTC (4 AM EST / 5 AM EDT)
  
  # Manual trigger option (can still trigger manually anytime)
  workflow_dispatch:
  
  # Push trigger option - uncomment if needed
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'crawler/**'

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: crawler/package-lock.json
      
      - name: Install crawler dependencies
        working-directory: ./crawler
        run: npm ci
      
      - name: Build crawler
        working-directory: ./crawler
        run: npm run build
      
      - name: Run crawler
        working-directory: ./crawler
        run: npm start
        env:
          CRAWLER_CONTACT_EMAIL: ${{ secrets.CRAWLER_CONTACT_EMAIL }}
          OUTPUT_PATH: ../public/data.json
      
      - name: Verify output
        run: |
          if [ -f public/data.json ]; then
            echo "✅ data.json created successfully"
            echo "File size: $(du -h public/data.json | cut -f1)"
          else
            echo "❌ data.json not found"
            exit 1
          fi
      
      # Auto-commit: Push updated data.json to trigger Vercel deployment
      - name: Commit and push data.json
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/data.json
          git diff --staged --quiet || git commit -m "chore: update web ecosystem data [skip ci]"
          git push
      
      # Alternative: Upload as artifact (useful for manual review)
      - name: Upload data.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: crawl-data
          path: public/data.json
          retention-days: 30

# Notes:
# - Set CRAWLER_CONTACT_EMAIL as a repository secret before enabling this workflow
#   (Repo Settings → Secrets and variables → Actions → New repository secret)
# - The [skip ci] tag prevents infinite loops if you enable push triggers
# - The artifact upload allows you to download and review data before committing
# - Consider adding a notification step (Slack, email, etc.) on failure
# - For production, consider adding tests to validate data.json structure

